✨ Added Toast API Support
cabaletta/baritone pull request #1958
Opened 2020-08-18 17:21 UTC by CDAGaming

This adds in a logAsToast and toastTimer option, and is a minified form of Indrit's initial implementation previously used from fabritone

2020-10-14 18:00 UTC, leijurv commented on src/api/java/baritone/api/utils/gui/BaritoneToast.java
> +public class BaritoneToast implements IToast
Doesn't follow baritone style at all. `{` on next line is cringe.

2020-10-14 18:00 UTC, leijurv commented on src/api/java/baritone/api/utils/Helper.java
> +            logToast(getPrefix(), component);
Not thread safe - pathing thread calls this sometimes. There was an `addScheduledTask` for a reason lol

2020-10-14 18:00 UTC, leijurv requested changes
based

2020-10-14 18:18 UTC, merged

2020-10-15 10:38 UTC, 0-x-2-2 commented on src/api/java/baritone/api/utils/gui/BaritoneToast.java
> +            toastGui.getMinecraft().fontRenderer.drawString(this.title, 18, 12, -11534256);
🤮 pasting from mojang i see ?

2020-10-15 14:06 UTC, l1ving commented on src/api/java/baritone/api/utils/gui/BaritoneToast.java
> +            toastGui.getMinecraft().fontRenderer.drawString(this.title, 18, 12, -11534256);
trolled

2020-10-15 14:40 UTC, CDAGaming commented on src/api/java/baritone/api/utils/gui/BaritoneToast.java
> +            toastGui.getMinecraft().fontRenderer.drawString(this.title, 18, 12, -11534256);
@RealIndrit is mojang confirmed? xD