notify users that their death position has been saved.
cabaletta/baritone pull request #2139
Opened 2020-11-01 17:23 UTC by scorbett123

fixes #90

2020-11-01 17:28 UTC, l1ving requested changes

2020-11-01 17:28 UTC, l1ving commented on src/main/java/baritone/behavior/MemoryBehavior.java
>          baritone.getWorldProvider().getCurrentWorld().getWaypoints().addWaypoint(new Waypoint("death", Waypoint.Tag.DEATH, ctx.playerFeet()));
change this to `baritone.getWorldProvider().getCurrentWorld().getWaypoints().addWaypoint(deathWaypoint);`

2020-11-01 17:33 UTC, l1ving approved these changes

2020-11-01 20:21 UTC, ZacSharp approved these changes

2021-02-07 12:20 UTC, scorbett123 commented
@leijurv and this one

2021-02-07 22:32 UTC, merged

2021-02-08 07:36 UTC, scorbett123 commented
Thanks