Add "RenderGoalAsBox" Setting
cabaletta/baritone pull request #2776
Opened 2021-05-25 17:51 UTC by thecakeisalie25

Does what it says, if this setting is set to true it'll disable the animations on the goals. 

Closes #2171 

## Screenshot:
![screenshot](https://user-images.githubusercontent.com/9502466/119544278-2c6bd180-bd57-11eb-8e74-1b7b909856ab.png)

2021-05-25 19:27 UTC, ZacSharp requested changes
I would give it a name related to animations (e.g. `renderGoalStatic`/`renderGoalAnimations`), because otherwise it suggests that it overrides `renderGoalXZBeacon`. Also the beacon beam should become static when animations are disabled.

2021-05-25 19:29 UTC, thecakeisalie25 commented
> 
> 
> I would give it a name related to animations (e.g. `renderGoalStatic`/`renderGoalAnimations`), because otherwise it suggests that it overrides `renderGoalXZBeacon`. Also the beacon beam should become static when animations are disabled.

How about renderGoalAnimated?

2021-05-25 19:30 UTC, ZacSharp commented
sure

2021-05-25 19:31 UTC, scorbett123 requested changes

2021-05-25 19:31 UTC, scorbett123 commented on src/main/java/baritone/utils/PathRenderer.java
> +            y = .999F;
```suggestion
            y = 0.999F;
```

2021-05-25 19:47 UTC, ZacSharp commented on src/api/java/baritone/api/Settings.java
>       * Render the goal as just a box instead of sick animated thingy
You missed to update the javadoc

2021-05-25 20:04 UTC, ZacSharp approved these changes

2021-05-26 18:30 UTC, leijurv commented on src/main/java/baritone/utils/PathRenderer.java
> +            y = 0.999F;
don't we all hate floating point 😹

2021-05-26 18:30 UTC, merged