Cleanup github actions
cabaletta/baritone pull request #2809
Opened 2021-06-14 08:46 UTC by FloGo3308

Just making it a little more consistent.
And `    - name: Set up JDK 9` was wrong cuz it runs on java 8, not 9

2021-06-14 12:54 UTC, scorbett123 approved these changes

2021-06-14 12:54 UTC, scorbett123 commented on .github/workflows/run_tests.yml
> +    - name: Set up JDK 8
Sorry, I obviously mistyped.

2021-06-14 20:39 UTC, ZacSharp approved these changes
Not sure about the renamed tasks but definitely a good thing in general.

2021-06-15 05:35 UTC, FloGo3308 commented
> Not sure about the renamed tasks but definitely a good thing in general.

What would you prefer then? I changed the build action to match the style of the test action becouse the build action still contained some stuff from the template.

Some questions:
- should I change the file name of the build action too?
- should I change the name of the build step to `Executing build` like the `Executing tests` the test action uses?(`Executing build` doesn't sound right though)
- why is the name(line 2) of the test action called `Tests` but the job(line 9) called `test`(without a s at the end)?(just a minor detail)

2021-06-15 22:11 UTC, ZacSharp commented
>     * should I change the file name of the build action too?

I think if the name doesn't mention gradle, then the name should not do it as well.
>     * should I change the name of the build step to `Executing build` like the `Executing tests` the test action uses?(`Executing build` doesn't sound right though)

That's sounds wrong as you said. I think this one is the only name using a progressive form.
>     * why is the name(line 2) of the test action called `Tests` but the job(line 9) called `test`(without a s at the end)?(just a minor detail)

Don't know, if you think it should be changed this is the pr for it.

As I said I'm not sure about the renames, which in this case means me having doubts about pretty much every line of this answer.
I'll send it anyway because I don't want to leave you without any answer at all.

2021-06-16 06:45 UTC, scorbett123 requested changes

2021-06-16 06:45 UTC, scorbett123 commented on .github/workflows/workflow_test.yml
> +    - name: Executing test
Change these both to the plural tests.

2021-06-16 06:53 UTC, FloGo3308 commented on .github/workflows/workflow_test.yml
> +    - name: Executing test
wdym with plural?

2021-06-16 08:02 UTC, scorbett123 commented on .github/workflows/workflow_test.yml
> +    - name: Executing test
tests not test

2023-10-01 19:13 UTC, closed without merging