Add new "Knight" movement option
cabaletta/baritone pull request #3014
Opened 2021-10-02 21:05 UTC by ShadowJonathan

Modelled after the diagonal movement option, this allows 2 "long" and 1 "side", allowing smoother movement instead of constantly going between diagonal<->linear.

Visualisation for y'all;

![image](https://user-images.githubusercontent.com/22740616/135731720-b41a5f9b-b0b3-43dd-ba65-02532913e470.png)

This bumps into (touchable) corners when they're able to walked into, not sure if that's a thing y'all want.

This doesn't go down or up one level, it's more intended to be nice when traversing a large platform somewhat diagonally.

This is probably un-optimised as heck.

2021-10-02 23:14 UTC, ZacSharp requested changes
I have done a quick review, but I'm not sure if this should be merged at all, because I don't see how it could enable Baritone to use paths it could not use before.
If there are no new possible paths this is simply post smoothing during pathing, which - as the name suggests - is better done once the path is found. Proper pos smoothing instead of a new movement could also allow for any angle flat moves without any additional calculation on the pathing thread. The disadvantage of post smoothing would be that it would consider a constant igzag of 2 blocks long segments as as good as a straight diagonal line, but imo that is better dealt with by changing to theta* than by trying to cover all diagonal lines (a lot) with their own movement.

2021-10-03 07:36 UTC, ShadowJonathan commented
Hmmm, this was indeed intended to be somewhat of a "smoothening" move, but your recommendation is to build in a specialised smoothing mechanism + switch to another algorithm for that?

I'd be interested in learning for it to accomplish that, it'd be interesting.

2021-10-03 07:41 UTC, ShadowJonathan commented on src/main/java/baritone/pathing/movement/movements/MovementKnight.java
> +        }
Yeah it's quite a simple check :/

I'll have to add it before this'd be approved, then

2021-10-08 22:09 UTC, ZacSharp commented
I definitely think post-smoothing would be a good addition, because it can significantly improve path lengths and make Baritone less painful to watch, without adding any overhead to the pathfinder itself.

I'm not sure on whether you should try switching Baritone to theta* (which is essentially a smarter way of post smoothing while pathing) because optimal algorithms are nice (and theta* isn't while a* can be) and because it adds significant overhead for all of the line of sight checks, while one of the first things mentioned in the readme is "Baritone focuses on reliability and particularly performance (it's over 30x faster than MineBot at calculating paths)."
Another option I'm not sure about is the multi-destination movements done for a (sadly closed) parkour pr, which would not require switching algorithms and could maybe maybe be a bit faster because it can be smarter about what to check.

My personal favourite currently is Anya, because it is pretty much the only optimal any-angle path finding algorithm I know and because it is mostly even faster than a*, but even though I haven't looked into it yet I have the feeling we can't use Anya in Baritone, just like a dozen other common performance improvement methods (most of them are for unweighted graphs or rely on blocked edges which Baritone does not have).

Also I'm a bit hesitant to give advice on such fundamental changes because after all it's leijurvs project and I don't want you do put a lot of effort into just to be told that it won't be used.

2021-10-11 15:56 UTC, ShadowJonathan commented
@ZacSharp you're not on libera when i checked just now, do you have any other networks you're on 24/7?

> Also I'm a bit hesitant to give advice on such fundamental changes because after all it's leijurvs project and I don't want you do put a lot of effort into just to be told that it won't be used.

Yeah i checked in with them on this, and i got a denial to switch away from A*. I think post-smoothening would be the way to go here, though im not exactly sure how to go about doing that.

2022-05-14 12:58 UTC, ShadowJonathan commented
I don't believe this'll go anywhere, so i'll close this but keep the branch up.

2022-05-14 12:58 UTC, closed without merging