handle multi subregion litematica schematics returning null blocks
cabaletta/baritone pull request #4363
Opened 2024-05-16 01:22 UTC by tolland

If the litematica schematic has multiple subregions that don't correspond to the full extent of the schematic, then "state" is null so the build crashes.

2024-05-26 01:18 UTC, ZacSharp requested changes
`placeAt` only queries the block after making sure it is in bounds so a null state at this point is a bug in `LitematicaSchematic`.

Also `logDirect` should be used for direct feedback and important things like error messages, not for borderline spam which can trigger 20 times per second.

2024-05-26 02:23 UTC, tolland commented
### Background and reproduction

Try to build this litematica schematic (which has 2 subregions) using baritone 1.10.2 under minecraft 1.20.4:

[subregion test1.litematic.zip](https://github.com/cabaletta/baritone/files/15445825/subregion.test1.litematic.zip)

It looks like this:
![2024-05-26_03 21 32](https://github.com/cabaletta/baritone/assets/91288/5061004f-6d53-492b-bbed-1a9976dfa981)

It crashes with null state for block error...

```
[03:10:13] [Render thread/INFO]: [CHAT] [Baritone] > litematica
[03:10:13] [Render thread/INFO]: [CHAT] [Baritone] Starting layer 0
[03:10:13] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26204()" because "desired" is null
	at baritone.api.schematic.SubstituteSchematic.desiredState(SubstituteSchematic.java:51) ~[baritone-unoptimized-fabric-1.10.2.jar:?]
	at baritone.process.BuilderProcess$2.desiredState(BuilderProcess.java:475) ~[baritone-unoptimized-fabric-1.10.2.jar:?]
	at baritone.process.BuilderProcess$BuilderCalculationContext.getSchematic(BuilderProcess.java:1104) ~[baritone-unoptimized-fabric-1.10.2.jar:?]
	at baritone.process.BuilderProcess.recalcNearby(BuilderProcess.java:644) ~[baritone-unoptimized-fabric-1.10.2.jar:?]
	at baritone.process.BuilderProcess.recalc(BuilderProcess.java:620) ~[baritone-unoptimized-fabric-1.10.2.jar:?]
	at baritone.process.BuilderProcess.onTick(BuilderProcess.java:505) ~[baritone-unoptimized-fabric-1.10.2.jar:?]
	at baritone.process.BuilderProcess.onTick(BuilderProcess.java:509) ~[baritone-unoptimized-fabric-1.10.2.jar:?]
	at baritone.process.BuilderProcess.onTick(BuilderProcess.java:439) ~[baritone-unoptimized-fabric-1.10.2.jar:?]
	at baritone.utils.PathingControlManager.executeProcesses(PathingControlManager.java:199) ~[baritone-unoptimized-fabric-1.10.2.jar:?]
	at baritone.utils.PathingControlManager.preTick(PathingControlManager.java:90) ~[baritone-unoptimized-fabric-1.10.2.jar:?]
	at baritone.behavior.PathingBehavior.onTick(PathingBehavior.java:104) ~[baritone-unoptimized-fabric-1.10.2.jar:?]
```

2024-05-26 02:35 UTC, tolland commented
So it was a while back when I looked at this, but the underlying issue is that baritone is returning true if the block is inside the extends of the schematic (assuming it is a rectangular cuboid) but the litematica schematic only defines the blocks for those subregions... and you can see from the image, that there are gaps between the minX and maxX etc

2024-05-26 02:49 UTC, ZacSharp commented
I wasn't saying that this doesn't happen, I was saying that you are fixing the wrong file. Just like you said yourself, `LitematicaSchematic.inSchematic` mistakenly returns `true` even outside subregions. `BuilderProcess` relying on a bounds checked position being in bounds is fine.

2024-05-26 03:24 UTC, tolland commented
Ah, I justed tested it... and yeah it doesn't fix the problem. So I will revisit.

2024-05-27 12:32 UTC, tolland commented
Any suggestions on how to get litematica mod running under the gradle debug build in intellij? dropping litematica.jar into the mods folder is not working

2024-05-27 14:28 UTC, rycbar0 commented on src/main/java/baritone/utils/schematic/format/defaults/LitematicaSchematic.java
> +
I agree that the default method needs a override however i have a few questions.
What is offsetSubregionMin doing? What happens if the schematic is rotated 90 degree? If im not mistaken the inSubregion() methods checks against the file in which the schematic isnt rotated.
Why not use
```
@Override
public boolean inSchematic(int x, int y, int z, BlockState currentState) {
    return getDirect(x, y, z) != null
}
```

2024-05-27 14:28 UTC, rycbar0 commented on src/main/java/baritone/utils/schematic/format/defaults/LitematicaSchematic.java
> +public class LitematicaSchematic extends StaticSchematic {
Why do you change all the method signatures? is it for your mock test?

2024-05-27 14:28 UTC, rycbar0 commented on src/main/java/baritone/utils/schematic/format/defaults/LitematicaSchematic.java
> +                        this.states[x][z][y] = blockList[bitArray.getAt(index)];
I dont remember why exactly i did it this way but im sure there was a reason for it.

2024-05-27 14:28 UTC, rycbar0 commented on src/main/java/baritone/utils/schematic/format/defaults/LitematicaSchematic.java
> +                    if (inSubregion(nbt, subReg, x + this.offsetMinCorner.getX(), y + offsetMinCorner.getY(), z + offsetMinCorner.getZ())) {
I assume this counteracts the changes in the next line in some way but i dont know how

2024-05-27 14:28 UTC, rycbar0 commented on src/main/java/baritone/utils/schematic/format/defaults/LitematicaSchematic.java
> +        return found;
a bit lengthy but not wrong as far as i can tell.
the xSize != 0 check is redundant (if size is 0, xMax = xMin  and x cant be >= and < to the same number)

2024-05-27 15:07 UTC, tolland commented
Thanks for the comments! I will address them.

I opened the PR because I thought it was a simple fix, but it seems quite involved. (e.g. rotating and mirroring multiple subregions...)

I think I will close the PR until I am more confident about how this might interact with the other stuff in LitematicaHelper

2024-05-27 15:07 UTC, closed without merging

2024-05-27 15:10 UTC, tolland commented on src/main/java/baritone/utils/schematic/format/defaults/LitematicaSchematic.java
> +public class LitematicaSchematic extends StaticSchematic {
yeah. to mock the class to avoid having to create the BuiltInRegistries stuff